FROM mongo:4.2
LABEL maintainer="stevenbetancurt@hotmail.com"

RUN apt-get update 

VOLUME [ "/backup" ]

# docker build -t stevensotelo/fauno_db:latest .
# docker tag xx stevensotelo/fauno_db:latest

# docker run --name fauno_db -p 27017:27017 --env-file ./.env -v D:/CIAT/Code/BID/dci_fauno_docker/src/database/data/data:/data/db -v D:/CIAT/Code/BID/dci_fauno_docker/src/database/data/backup:/backup -d stevensotelo/fauno_db:latest

